services:
  pubmed_summarizer:
    build: .
    ports:
      - "8505:8505"
    volumes:
      - /mnt/storage:/mnt/storage
      - .:/streamlit
    networks:
      - klims_shared_network
    container_name: pubmed_summarizer
    environment:
      - GIT_PYTHON_REFRESH=quiet

networks:
  klims_shared_network:
    driver: bridge
